<?php
/**
 * Created By
 * Date:2021/6/10
 * Author:jhwu
 */

namespace App\Models;


class ModelBase extends \EasySwoole\ORM\AbstractModel
{
    protected $pre = 'wd_';

    public function __construct(array $data = [])
    {
        $this->tableName = $this->pre . $this->tableName;
        parent::__construct($data);
    }

    public function tableName(?string $name = null, bool $is_temp = false)
    {
        if ($name !== null) $name = $this->pre.$name;
        return parent::tableName($name, $is_temp); // TODO: Change the autogenerated stub
    }
}